output "db_endpoint" {
  description = "The application will be connect to the database using this address."
  value       = "${module.db.this_db_instance_endpoint}"
}

output "eks_endpoint" {
  description = "The EKS master nodes and API Server is exposed on this endpoint."
  value       = "${module.eks.cluster_endpoint}"
}

output "ecr_endpoint" {
  description = "The Docker images are pulled and pushed to this repository using this endpoint."
  value       = "${aws_ecr_repository.nodeapprepo.repository_url}"
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = "${module.eks.kubeconfig}"
}

output "workers_asg_names" {
  description = "Names of the autoscaling groups containing workers."
  value       = "${concat(aws_autoscaling_group.workers.*.id, aws_autoscaling_group.workers_launch_template.*.id)}"
}