apiVersion: v1
kind: Service
metadata:
  name: nodeapp-api-svc
  labels:
    app: nodeapp
spec:
  ports:
  - port: 3300
    protocol: TCP
    targetPort: 3000
  #clusterIP: None
  selector:
    role: api

