apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nodeapp-api
  labels:
     app: nodeapp
     role: api
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: nodeapp
      role: api
  template:
    metadata:
      labels:
        app: nodeapp
        role: api
    spec:
      containers:
      - name: nodeapp-api
        image: 744494341535.dkr.ecr.us-east-1.amazonaws.com/sample-app:{{API_TAG}}
        env:
            - name: DB
              value: "postgres://testuserdb:heartbeathealth@hr15psbwwbq6mmi.cj4cnpmwpa9z.us-east-1.rds.amazonaws.com:5432/testDB"
        ports:
        - containerPort: 3000
