apiVersion: v1
kind: Service
metadata:
  name: nodeapp-web-svc
  labels:
    app: nodeapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  #clusterIP: None
  selector:
    role: web

